name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Checkout build branch
        run: |
          git fetch origin
          git switch -C build origin/build || git switch --orphan build

      - name: Copy build files
        run: |
          rm -rf ./*
          cp -r build/* .

      - name: Commit and push build files
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "brunomachado3818@gmail.com"
          git config --global user.name "bruno15b"
          git add .
          git commit -m "Build: (${GITHUB_SHA}) ${GITHUB_REF_NAME}"
          git push -u origin build --force
s