name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "brunomachado3818@gmail.com"
          git config --global user.name "bruno15b"
          git add build/
          git commit -m "Build: (${GITHUB_SHA}) ${GITHUB_REF_NAME}"
          git push origin HEAD:build
